
import { Language, Lesson, DailyGoal } from './types';

export const LANGUAGES: Language[] = [
  { id: 'en-us', name: 'English (US)', nativeName: 'English', flag: '🇺🇸' },
  { id: 'th', name: 'Thai', nativeName: 'ภาษาไทย', flag: '🇹🇭' },
  { id: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { id: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { id: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { id: 'jp', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { id: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { id: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { id: 'ua', name: 'Ukrainian', nativeName: 'Українська', flag: '🇺🇦' },
  { id: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ', flag: '🇪🇷' },
  { id: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { id: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { id: 'se', name: 'Swedish', nativeName: 'Svenska', flag: '🇸🇪' },
  { id: 'si', name: 'Slovenian', nativeName: 'Slovenščina', flag: '🇸🇮' },
  { id: 'sk', name: 'Slovak', nativeName: 'Slovenčina', flag: '🇸🇰' },
  { id: 'rs', name: 'Serbian', nativeName: 'Српски', flag: '🇷🇸' },
  { id: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { id: 'ro', name: 'Romanian', nativeName: 'Română', flag: '🇷🇴' },
  { id: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { id: 'pt-pt', name: 'Portuguese (PT)', nativeName: 'Português', flag: '🇵🇹' },
  { id: 'pt-br', name: 'Portuguese (BR)', nativeName: 'Português', flag: '🇧🇷' },
  { id: 'pl', name: 'Polish', nativeName: 'Polski', flag: '🇵🇱' },
  { id: 'fa', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷' },
  { id: 'nn', name: 'Nynorsk', nativeName: 'Nynorsk', flag: '🇳🇴' },
  { id: 'no', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴' },
  { id: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { id: 'mk', name: 'Macedonian', nativeName: 'Македонски', flag: '🇲🇰' },
  { id: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', flag: '🇱🇹' },
  { id: 'lv', name: 'Latvian', nativeName: 'Latviešu', flag: '🇱🇻' },
  { id: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { id: 'kz', name: 'Kazakh', nativeName: 'Қазақша', flag: '🇰🇿' },
  { id: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { id: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { id: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { id: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { id: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { id: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { id: 'gr', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { id: 'ge', name: 'Georgian', nativeName: 'ქართული', flag: '🇬🇪' },
  { id: 'ee', name: 'Estonian', nativeName: 'Eesti', flag: '🇪🇪' },
  { id: 'eo', name: 'Esperanto', nativeName: 'Esperanto', flag: '🌍' },
  { id: 'ady', name: 'Adyghe', nativeName: 'Адыгабзэ', flag: '🇷🇺' },
  { id: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', flag: '🇿🇦' },
  { id: 'am', name: 'Amharic', nativeName: 'አማርኛ', flag: '🇪🇹' },
  { id: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { id: 'hy', name: 'Armenian', nativeName: 'Հայերեն', flag: '🇦🇲' },
  { id: 'be', name: 'Belarusian', nativeName: 'Беларуская', flag: '🇧🇾' },
  { id: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { id: 'bs', name: 'Bosnian', nativeName: 'Bosanski', flag: '🇧🇦' },
  { id: 'bg', name: 'Bulgarian', nativeName: 'Български', flag: '🇧🇬' },
  { id: 'ca', name: 'Catalan', nativeName: 'Català', flag: '🇦🇩' },
  { id: 'zh', name: 'Chinese (Simplified)', nativeName: '简体中文', flag: '🇨🇳' },
  { id: 'hr', name: 'Croatian', nativeName: 'Hrvatski', flag: '🇭🇷' },
  { id: 'cs', name: 'Czech', nativeName: 'Čeština', flag: '🇨🇿' },
  { id: 'da', name: 'Danish', nativeName: 'Dansk', flag: '🇩🇰' },
  { id: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
];

export const INITIAL_LESSON_DATA = (): Lesson[] => {
  const topics = [
    { title: 'Greetings & Basics', icon: '👋', cat: 'Essential', color: 'bg-yellow-400', grammar: 'Polite particles vary by gender and context.' },
    { title: 'Street Food Tour', icon: '🍲', cat: 'Food', color: 'bg-orange-400', grammar: 'Using classifiers for ordering different types of dishes.' },
    { title: 'Finding Your Way', icon: '🗺️', cat: 'Travel', color: 'bg-blue-400', grammar: 'Prepositions of place and movement indicators.' },
    { title: 'Emergency Help', icon: '🆘', cat: 'Essential', color: 'bg-red-500', grammar: 'Direct imperative verb forms for urgent situations.' },
    { title: 'At the Market', icon: '🛍️', cat: 'Shopping', color: 'bg-emerald-400', grammar: 'Numerical systems and currency classifiers.' },
    { title: 'Social Media', icon: '📱', cat: 'Digital', color: 'bg-purple-400', grammar: 'Informal slang and abbreviation rules.' },
    { title: 'Nature & Parks', icon: '🌳', cat: 'Environment', color: 'bg-green-500', grammar: 'Adjective placement for describing scenery.' },
    { title: 'Space Exploration', icon: '🚀', cat: 'Science', color: 'bg-indigo-500', grammar: 'Technical loanwords and future tense usage.' },
    { title: 'Ancient Legends', icon: '🐉', cat: 'Culture', color: 'bg-amber-500', grammar: 'Narrative past tense and mythological honorifics.' },
    { title: 'Tech Startup', icon: '💻', cat: 'Business', color: 'bg-cyan-500', grammar: 'Professional honorifics in office environments.' },
    { title: 'Daily Routine', icon: '⏰', cat: 'Daily Life', color: 'bg-rose-400', grammar: 'Time markers and frequency adverbs.' },
    { title: 'Pet Care', icon: '🐕', cat: 'Home', color: 'bg-teal-400', grammar: 'Possessive particles for relationships.' },
    { title: 'Music & Art', icon: '🎨', cat: 'Hobbies', color: 'bg-fuchsia-400', grammar: 'Verbs of emotion and sensory descriptions.' },
    { title: 'In the Kitchen', icon: '🔪', cat: 'Home', color: 'bg-lime-500', grammar: 'Recipe-specific imperatives and sequence markers.' },
    { title: 'Sports & Fitness', icon: '🏃', cat: 'Health', color: 'bg-violet-500', grammar: 'Comparison structures (faster, stronger).' },
    { title: 'Weather Forecast', icon: '🌤️', cat: 'Daily Life', color: 'bg-sky-400', grammar: 'Impersonal weather verbs and condition markers.' },
    { title: 'Romantic Dinner', icon: '🕯️', cat: 'Social', color: 'bg-pink-500', grammar: 'Softening particles for polite invitations.' },
    { title: 'Public Transport', icon: '🚌', cat: 'Travel', color: 'bg-zinc-500', grammar: 'Locative prepositions for commute.' },
    { title: 'Coding Basics', icon: '⌨️', cat: 'Digital', color: 'bg-slate-600', grammar: 'Conditional logic structures (if/then).' },
    { title: 'Mindfulness', icon: '🧘', cat: 'Health', color: 'bg-emerald-300', grammar: 'Stative verbs and continuous present.' },
    { title: 'Global News', icon: '📰', cat: 'Culture', color: 'bg-blue-400', grammar: 'Formal reporting speech and quoted speech rules.' },
    { title: 'Aviation History', icon: '✈️', cat: 'History', color: 'bg-neutral-500', grammar: 'Historical past tense markers.' },
    { title: 'Gardening Tips', icon: '🌻', cat: 'Hobbies', color: 'bg-yellow-300', grammar: 'Spatial descriptors for plant placement.' },
    { title: 'Fashion Design', icon: '👗', cat: 'Art', color: 'bg-pink-300', grammar: 'Adjective ordering for materials and colors.' },
    { title: 'Coffee Culture', icon: '☕', cat: 'Social', color: 'bg-stone-600', grammar: 'Intensifiers for adjectives (very, slightly).' },
    { title: 'Ocean Mysteries', icon: '🐋', cat: 'Environment', color: 'bg-blue-700', grammar: 'Superlatives for describing extremes.' },
    { title: 'Movie Night', icon: '🎬', cat: 'Entertainment', color: 'bg-red-600', grammar: 'Expressing subjective opinions and reactions.' },
    { title: 'Board Games', icon: '🎲', cat: 'Social', color: 'bg-yellow-600', grammar: 'Modality of rules (can, must, shouldn\'t).' },
    { title: 'Architecture', icon: '🏛️', cat: 'Art', color: 'bg-stone-400', grammar: 'Material nouns and structural descriptors.' },
    { title: 'Cryptocurrency', icon: '₿', cat: 'Business', color: 'bg-orange-500', grammar: 'Dynamic financial vocabulary.' },
    { title: 'Camping Trip', icon: '🏕️', cat: 'Travel', color: 'bg-green-700', grammar: 'Survival vocabulary and item nouns.' },
    { title: 'Astronomy', icon: '🔭', cat: 'Science', color: 'bg-slate-900', grammar: 'Compound nouns for celestial bodies.' },
    { title: 'Volunteering', icon: '🤝', cat: 'Social', color: 'bg-rose-300', grammar: 'Benefactive particles (doing something for others).' },
    { title: 'Legal Matters', icon: '⚖️', cat: 'Business', color: 'bg-gray-800', grammar: 'Formal negative particles and strict syntax.' },
    { title: 'Baking Bread', icon: '🍞', cat: 'Hobbies', color: 'bg-amber-300', grammar: 'Process-oriented transition words.' },
    { title: 'Robotics', icon: '🤖', cat: 'Technology', color: 'bg-zinc-300', grammar: 'Action-result relationship markers.' },
    { title: 'Photography', icon: '📷', cat: 'Art', color: 'bg-gray-700', grammar: 'Descriptors for light, focus, and perspective.' },
    { title: 'Public Speaking', icon: '🎤', cat: 'Skills', color: 'bg-indigo-600', grammar: 'Emphasis particles for spoken discourse.' },
    { title: 'Mountain Climbing', icon: '🧗', cat: 'Sports', color: 'bg-slate-500', grammar: 'Physical exertion state verbs.' },
    { title: 'Zoo Visit', icon: '🦁', cat: 'Education', color: 'bg-orange-300', grammar: 'Pluralization rules for animal species.' },
    { title: 'Airport Check-in', icon: '🎫', cat: 'Travel', color: 'bg-sky-600', grammar: 'Standard declarative phrases for services.' },
    { title: 'Sustainable Living', icon: '♻️', cat: 'Environment', color: 'bg-emerald-600', grammar: 'Modal verbs of obligation and ethics.' },
    { title: 'Library Study', icon: '📚', cat: 'Education', color: 'bg-amber-800', grammar: 'Academic compound nouns.' },
    { title: 'Theme Park', icon: '🎡', cat: 'Entertainment', color: 'bg-pink-600', grammar: 'Exclamatory sentence structures.' },
    { title: 'Winter Sports', icon: '⛷️', cat: 'Sports', color: 'bg-blue-100', grammar: 'Sensory descriptors for cold and motion.' },
    { title: 'Urban Legend', icon: '👻', cat: 'Culture', color: 'bg-purple-800', grammar: 'Mood-setting syntax and particle choice.' },
    { title: 'DIY Projects', icon: '🔨', cat: 'Home', color: 'bg-orange-900', grammar: 'Step-by-step logical connectors.' },
    { title: 'Luxury Travel', icon: '💎', cat: 'Travel', color: 'bg-indigo-300', grammar: 'Extremely polite register for high-end service.' },
    { title: 'Ancient Egypt', icon: '🏺', cat: 'History', color: 'bg-yellow-800', grammar: 'Past tense markers for ancient history.' },
    { title: 'Modern Dance', icon: '💃', cat: 'Art', color: 'bg-rose-500', grammar: 'Fluid motion action verbs.' },
    { title: 'Car Repair', icon: '🔧', cat: 'Skills', color: 'bg-gray-400', grammar: 'Part-whole relationship markers.' },
    { title: 'Virtual Reality', icon: '🥽', cat: 'Technology', color: 'bg-cyan-600', grammar: 'Spatial prepositions in digital space.' },
    { title: 'Chess Strategy', icon: '♟️', cat: 'Hobbies', color: 'bg-stone-800', grammar: 'Complex conditional logic (if/then/else).' },
    { title: 'Yoga Flow', icon: '🧘‍♀️', cat: 'Health', color: 'bg-purple-300', grammar: 'Anatomical imperative alignment.' },
    { title: 'Scuba Diving', icon: '🤿', cat: 'Travel', color: 'bg-blue-900', grammar: 'Pressure and depth related measurements.' },
    { title: 'Pottery Class', icon: '🏺', cat: 'Hobbies', color: 'bg-amber-700', grammar: 'Material state change verbs (soft, hard).' },
    { title: 'High-speed Rail', icon: '🚅', cat: 'Travel', color: 'bg-zinc-200', grammar: 'Time and distance ratio structures.' },
    { title: 'Renewable Energy', icon: '☀️', cat: 'Environment', color: 'bg-yellow-200', grammar: 'Technical passive voice for systems.' },
    { title: 'Virtual Concerts', icon: '🎧', cat: 'Entertainment', color: 'bg-fuchsia-600', grammar: 'Digital experience descriptors.' },
    { title: 'E-commerce', icon: '🛒', cat: 'Business', color: 'bg-blue-500', grammar: 'Transactional verbs and feedback syntax.' }
  ];

  return topics.map((t, i) => ({
    id: `l${i}`,
    title: t.title,
    category: t.cat,
    difficulty: i < 15 ? 'Beginner' : i < 35 ? 'Intermediate' : 'Advanced',
    progress: i === 0 ? 100 : 0, 
    icon: t.icon,
    color: t.color,
    grammarNotes: t.grammar,
    vocabulary: [
      `${t.title} Vocab A`, 
      `${t.title} Vocab B`, 
      `${t.title} Vocab C`, 
      `${t.title} Phrase`
    ],
    needsReview: i % 12 === 0
  }));
};

export const MOCK_LESSONS: Lesson[] = INITIAL_LESSON_DATA();

export const MOCK_QUIZ_GREETINGS = [
  {
    id: 'q1',
    type: 'MATCH',
    prompt: 'Match the phrases to their meanings:',
    pairs: [
      { key: 'Hello', value: 'Greeting' },
      { key: 'Bread', value: 'Food' },
      { key: 'Car', value: 'Vehicle' },
      { key: 'Blue', value: 'Color' }
    ]
  },
  {
    id: 'q2',
    type: 'MULTIPLE_CHOICE',
    prompt: 'Which one is a polite greeting?',
    options: ['Hi', 'Get out', 'I am hungry', 'Goodbye'],
    correctAnswer: 'Hi'
  },
  {
    id: 'q3',
    type: 'ARRANGE',
    prompt: 'Order the words to form a valid sentence:',
    options: ['I', 'am', 'learning', 'fast'],
    correctAnswer: ['I', 'am', 'learning', 'fast']
  }
];

export const MOCK_GOALS: DailyGoal[] = [
  { id: 'g1', title: 'Complete 1 Lesson', completed: false, target: 1, current: 0, icon: '📚' },
  { id: 'g2', title: 'Practice Chat for 5 mins', completed: true, target: 1, current: 1, icon: '💬' },
  { id: 'g3', title: 'Earn 100 XP', completed: false, target: 100, current: 45, icon: '⚡' },
];
